### ISSUE TITLE
Dask dashboards not working for Coiled cluster

### ISSUE THREAD

**Issue by hugobowne** [coiled/data-science-at-scale#28] opened 2020-10-27 04:26 UTC
When I execute the Coiled part of [our overview notebook](https://github.com/coiled/data-science-at-scale/blob/master/notebooks/data-umbrella-2020-10-27/0-overview.ipynb), the Dask dashboarding doesn't seem to work.

The relevant section of Jupyter Lab is greyed out like this.

![Screen Shot 2020-10-27 at 3 21 32 pm](https://user-images.githubusercontent.com/4182382/97256881-5ebc5b80-1868-11eb-86d4-0b8503e95dc2.png)

any thoughts, @jrbourbeau ?

**Comment by jrbourbeau** [comment] 2020-10-27 20:44
Hmm, thanks for reporting @hugobowne -- I'm able to reproduce. There hasn't been a `dask-labextension` release since August, so I suspect this is something on our end. I can test things our with an older version of bokeh / distributed to see if there's been a recent regression

**Comment by jrbourbeau** [comment] 2020-11-12 21:51
Closing as this issue has been resolved upstream

**Closed as completed by jrbourbeau** 2020-11-12 21:51 UTC
